---
title: "Milestone 4"
author: "Katherine Enright"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library("csvy")
library(yaml)
```

```{r read_data}
#I installed the csvy package to read in this file
identity_data <- read_csvy("raw-data/TP190602_EI_final_v1_POP.csvy")

#In the result table, the columnn names are listed as "Q001", "Q002A" etc; I need to figure out which questions in the survey these correspond to.

#The csvy file format is a csv file preceded by a YAML metadata header. The information about the meaning of the question and value codes is contained within this header.

yaml_data <- get_yaml_header("raw-data/TP190602_EI_final_v1_POP.csvy")

#Each column in the csv contains a "name" attribute that is displayed, in addition to "title" (the title of the question), "type" (variable type), and "labels" (possible answers).

#My goal is to link this metadata to the table in identity_data. Is there a way to automatically assign the corresponding question data so that "title" displays instead of "name"?

#I installed the library(yaml) to turn the yaml into R objects. On further exploration, this might not be necessary; I'll keep it around for the time being.

```

```{r initial_plot}
#My goal here is to plot the variable "strength of identity as a Hongkonger" against the age of the participants. One common assumption is that the younger generation in Hong Kong have a stronger unique Hong Kong as opposed to Chinese identity: does the data hold up?

#Question name: Q002A
#title:"Please use a scale of 0-10 to rate your strength of identity as a Hongkonger, with 10 indicating extremely strong, 0 indicating extremely weak, and 5 indicating half-half"
#Labels: Refuse to answer: -99.0                                                               Don't know / hard to say: 8888.0


#title: Age group"                                                                       #  labels:"                                                                                   
#    Refuse to answer: -99.0"                                                                 
#    18-29: 1.0"                                                                              
#    30-39: 2.0"                                                                              
#    40-49: 3.0"                                                                              
#    50-59: 4.0"                                                                              
#    60-69: 5.0"                                                                              
 #   70 or above: 6.0"                                                                        
#I think a boxplot would be the best way to display this data.
# Convert the variablefrom a numeric to a factor variable

identity_data$agegp <- as.factor(identity_data$agegp)

plot_data <- identity_data %>% 
  select(Q002A, agegp) %>% 
  filter(Q002A != "8888",agegp %in% 1:6)

ggplot(plot_data,
       aes(x=agegp, y=Q002A, alpha=0.3), group=agegp) +
      geom_boxplot(alpha=0.3,fill="light blue") +
      labs(title = "Strength of Identity as Hong Konger by Age Group", 
           x= "Age group",
           y= "Srength of Identity") +
  geom_jitter(shape=16, position=position_jitter(0.3), alpha=0.5, color="blue")

#There was an uneven number of responses across the age groups; should I use a weight to account for this?
age_distro <- plot_data %>% count(agegp)

#my results seemed suspicous, so I'm going to create a function to compare the average identity score across age groups
avg_by_age <-  function(.x) {
  plot_data %>% filter(agegp == .x) %>% summarise(avg=mean(Q002A))
}
```

